// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL6ZWiUQM8LOx7OILUoeDOavw3HzDoqME',
    appId: '1:5485136644:web:9197454ae0de09cca19e51',
    messagingSenderId: '5485136644',
    projectId: 'uaut-87430',
    authDomain: 'uaut-87430.firebaseapp.com',
    storageBucket: 'uaut-87430.firebasestorage.app',
    measurementId: 'G-YDWLQWG3WG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjeK4cvjcuSjh7ZoziDZU0ylYEp1jEMRc',
    appId: '1:5485136644:android:bbdadbd5795b45bfa19e51',
    messagingSenderId: '5485136644',
    projectId: 'uaut-87430',
    storageBucket: 'uaut-87430.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWRZeZFU595rBFFwiUle23kq3tOzT7mqE',
    appId: '1:5485136644:ios:30e470ffae5fb23ca19e51',
    messagingSenderId: '5485136644',
    projectId: 'uaut-87430',
    storageBucket: 'uaut-87430.firebasestorage.app',
    iosBundleId: 'com.example.bustracker007',
  );
}
